name: Test Project

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install pytest

      - name: Run tests
        run: pytest test.py -s

      - name: Build
        run: echo "Building project..."

      - name: Deploy
        run: echo "Deploying..."

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint flake8 mypy black isort

      - name: Run Flake8
        run: flake8 .

      - name: Run Mypy
        run: mypy .

      - name: Check Black formatting
        run: black --line-length=120 --check .

      - name: Check Isort formatting
        run: isort --check-only .

      - name: Run tests
        run: pytest test.py -s
