name: Test Project

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}

jobs:
  test:
    env:
      TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 .

      - name: Run Mypy
        run: mypy .

      - name: Check Black formatting
        run: black --line-length=120 --check .

      - name: Check Isort formatting
        run: isort --check-only .

      - name: Create dummy test report
        run: echo "Some test report!" > test-report.txt

      - name: Run tests
        id: run-tests
        run: pytest test.py -s

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.txt

      - name: Output info
        run: echo "USER - ${{ env.TEST_POSTGRES_USER }}, DB_NAME - ${{ env.TEST_DB_NAME }}, PASSWORD - ${{ env.TEST_POSTGRES_PASSWORD }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.dummy-script-file }}
    steps:
      - name: Build
        run: |
          echo "Building project..."
          # Create a dummy artifact file
          echo "This is a dummy artifact" > dummy_artifact.txt
      - name: Publish Dummy filename
        id: publish
        run: find *.txt -type f -execdir echo 'dummy-script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dummy-artifact
          path: dummy_artifact.txt
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dummy-artifact
      - name: Output content
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."

  report:
    needs: [ deploy ]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
