name: Test Project
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint flake8 mypy black isort
      - name: Run Flake8
        run: flake8 .
      - name: Run Mypy
        run: mypy .
      - name: Run Black formatter check
        run: black --check .
      - name: Run Isort check
        run: isort --check-only .
      - name: Run tests
        run: pytest test.py -s
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install pytest
      - name: Build
        run: echo "Building project..."
      - name: Deploy
        run: echo "Deploying..."
